# Generated by Django 4.0.4 on 2024-04-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_replies_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies_count',
        ),
    ]
